<?xml version="1.0" encoding="utf-8"?><Database Name="countertop" Class="dbCounterTopsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=stusql.ckwia8qkgyyj.us-east-1.rds.amazonaws.com;Initial Catalog=countertop;Persist Security Info=True;User ID=260counterTop" SettingsObjectName="CuttingEdgeInvMgmtSystem.Properties.Settings" SettingsPropertyName="countertopConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Colors" Member="Colors">
    <Type Name="Color">
      <Column Name="ColorID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Color" Member="Color1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Color_BarTop" Member="BarTops" ThisKey="ColorID" OtherKey="ColorID" Type="BarTop" />
      <Association Name="Color_Kitchen" Member="Kitchens" ThisKey="ColorID" OtherKey="ColorID" Type="Kitchen" />
      <Association Name="Color_Vanity" Member="Vanities" ThisKey="ColorID" OtherKey="ColorID" Type="Vanity" />
    </Type>
  </Table>
  <Table Name="dbo.BarTop" Member="BarTops">
    <Type Name="BarTop">
      <Column Name="BarTopID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ColorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Length" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Width" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Color_BarTop" Member="Color" ThisKey="ColorID" OtherKey="ColorID" Type="Color" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Kitchen" Member="Kitchens">
    <Type Name="Kitchen">
      <Column Name="KitchenID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ColorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Length" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Color_Kitchen" Member="Color" ThisKey="ColorID" OtherKey="ColorID" Type="Color" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Vanity" Member="Vanities">
    <Type Name="Vanity">
      <Column Name="VanityID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ColorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Length" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Color_Vanity" Member="Color" ThisKey="ColorID" OtherKey="ColorID" Type="Color" IsForeignKey="true" />
    </Type>
  </Table>
</Database>